[build-system]
requires = [
    "hatchling>=1.13.0",
    "hatch-vcs>=0.3.0",
]
build-backend = "hatchling.build"

[project]
name = "specterpy"
dynamic = ["version"]
description = "framework for defining, building, and evaluating generalized shape observables for collider physics"
readme = "README.md"
license = { text = "MIT" }  # SPDX short identifier
requires-python = ">=3.7"
authors = [
    { name = "Rikab Gambhir", email = "rikab@mit.edu" },
]
keywords = [
    "shape observables",
    "jet physics",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
    "jax>=0.4.13",
    "jaxlib>=0.4.13",
    "scipy>=1.5.1",
    "matplotlib>=3.5.0",
    "numpy",  # compatible versions controlled through scipy
    "rikabplotlib",
    "particleloader"
]

[tool.hatch.metadata]
allow-direct-references = true

[project.urls]
Documentation = "https://github.com/rikab/SPECTER"
Homepage = "https://github.com/rikab/SPECTER"
"Issue Tracker" = "https://github.com/rikab/SPECTER/issues"
"Releases" = "https://github.com/rikab/SPECTER/releases"
"Source Code" = "https://github.com/rikab/SPECTER"


[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.hatch.build.hooks.vcs]
version-file = "src/pyspecter/_version.py"

[tool.hatch.build.targets.sdist]
# only-include files that are needed to ignore examples
only-include = [
    "/src",
    "/LICENSE",
    "/README.md",
    "/pyproject.toml",
]

[tool.hatch.build.targets.wheel]
packages = ["src/pyspecter"]

[tool.coverage.run]
source = ["pyspecter"]
branch = true

[tool.coverage.report]
precision = 1
sort = "cover"
show_missing = true
